export function getPrivacyHtml(): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Turf Runner — Privacy Policy</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      background: #0a0a12; color: #c8c8d0; line-height: 1.7;
      padding: 24px; max-width: 720px; margin: 0 auto;
    }
    h1 { color: #ff6a00; font-size: 28px; margin-bottom: 8px; }
    h2 { color: #e8e8ec; font-size: 20px; margin-top: 32px; margin-bottom: 12px; }
    p, li { margin-bottom: 10px; font-size: 15px; }
    ul { padding-left: 24px; }
    a { color: #ff6a00; text-decoration: none; }
    a:hover { text-decoration: underline; }
    .updated { color: #8a8a96; font-size: 13px; margin-bottom: 24px; }
    .back { display: inline-block; margin-top: 32px; padding: 10px 20px; background: #1a1a2e; border: 1px solid #2a2a3e; border-radius: 8px; color: #e8e8ec; }
    .back:hover { background: #2a2a3e; text-decoration: none; }
  </style>
</head>
<body>
  <h1>Privacy Policy</h1>
  <div class="updated">Last updated: April 2, 2026</div>

  <p>Turf Runner ("the App") is a social running strategy game. This policy explains what data we collect, how we use it, and your rights.</p>

  <h2>1. Data We Collect</h2>

  <p><strong>From Strava (via OAuth):</strong></p>
  <ul>
    <li><strong>Strava athlete ID</strong> — used as your unique account identifier</li>
    <li><strong>Name</strong> (first and last) — used as your display name in the app</li>
    <li><strong>OAuth tokens</strong> — access token, refresh token, and expiry for API access</li>
    <li><strong>Activity IDs</strong> — stored solely to prevent the same run from being counted twice</li>
  </ul>

  <p><strong>Generated by gameplay:</strong></p>
  <ul>
    <li>Territory data (H3 hex cell IDs and run point totals)</li>
    <li>Discovered cells (fog of war progress)</li>
    <li>Skills, group membership, and RP balance</li>
    <li>A session cookie for authentication</li>
  </ul>

  <h2>2. Data We Do NOT Collect or Store</h2>
  <ul>
    <li><strong>No GPS tracks or coordinates</strong> — your run's GPS data is processed entirely in your browser to determine which hex cells you passed through. The raw GPS path is never sent to or stored on our servers.</li>
    <li><strong>No Strava activity details</strong> — no pace, distance, heart rate, elevation, or route data</li>
    <li><strong>No email address or password</strong> — authentication is handled entirely through Strava</li>
    <li><strong>No contacts or social data</strong> from Strava</li>
  </ul>

  <h2>3. How We Use Your Data</h2>
  <ul>
    <li><strong>Strava athlete ID and tokens</strong>: to authenticate you and import your runs</li>
    <li><strong>Display name</strong>: shown to other players in leaderboards and group rosters</li>
    <li><strong>Activity IDs</strong>: to prevent duplicate run submissions</li>
    <li><strong>Gameplay data</strong>: to operate the game — territory ownership, scoring, skills, and group features</li>
  </ul>

  <h2>4. Location Privacy</h2>
  <p>Your exact running locations are <strong>never stored or shared</strong>. The app converts GPS coordinates into H3 hexagonal grid cells (approximately 174 meters across) in your browser. Only the cell IDs are sent to the server. Other players can see which cells are owned, but cannot determine where you specifically ran or your exact route.</p>

  <h2>5. Data Sharing</h2>
  <p>We do not sell, rent, or share your personal data with third parties. The only external service we integrate with is Strava, and data flows are limited to the OAuth authentication described above.</p>

  <h2>6. Data Retention & Deletion</h2>
  <ul>
    <li><strong>Disconnecting Strava</strong> (from the app's Settings or from Strava's connected apps page) will immediately delete all Strava-sourced data: your Strava ID, name, OAuth tokens, and activity ID references.</li>
    <li><strong>Game data is retained</strong> after disconnecting — your RP, territory, skills, and group membership remain. This is app-generated data, not Strava data.</li>
    <li>If you want all data deleted entirely, contact us and we will remove your account and all associated data.</li>
  </ul>

  <h2>7. Strava Compliance</h2>
  <p>This app uses the Strava API and complies with <a href="https://www.strava.com/legal/api" target="_blank">Strava's API Agreement</a>. We handle deauthorization webhooks, do not cache activity data beyond activity IDs for deduplication, and display required Strava attribution.</p>

  <h2>8. Cookies</h2>
  <p>We use a single session cookie (<code>turf_session</code>) to keep you logged in. It is HttpOnly, SameSite=Lax, and expires after 30 days. We do not use tracking cookies or third-party analytics.</p>

  <h2>9. Security</h2>
  <p>Data is stored on Cloudflare's infrastructure with encryption at rest. OAuth tokens are stored server-side and never exposed to the browser. All communications use HTTPS.</p>

  <h2>10. Changes to This Policy</h2>
  <p>We may update this policy as the app evolves. Changes will be reflected by updating the "Last updated" date above.</p>

  <h2>11. Contact</h2>
  <p>For privacy questions or data deletion requests, contact us at: <strong>[your-email@example.com]</strong></p>

  <a class="back" href="/">← Back to Turf Runner</a>
</body>
</html>`;
}
